import express from "express";
import usersRoutes from "./user.routes.js";
import authRoutes from "./auth.routes.js";
import postRoutes from "./post.routes.js";
import commentRoutes from "./comments.routes.js";
import likeRoutes from "./like.routes.js";
import chatRoutes from "./chat.routes.js";
import messageRoutes from "./message.routes.js";
import notificationRoutes from "./notification.routes.js";
const router = express.Router({ mergeParams: true });
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/post", postRoutes);
router.use("/comment", commentRoutes);
router.use("/like", likeRoutes);
router.use("/chat", chatRoutes);
router.use("/message", messageRoutes);
router.use("/notification", notificationRoutes);
export default router;
